<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spreadsheet" nsURI="http://www.kermeta.org/spreadsheet" nsPrefix="spreadsheet">
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true" eOpposite="#//Expression/cell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" eType="#//Cell" eOpposite="#//Cell/expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinExpression" eSuperTypes="#//Expression">
    <eOperations name="function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="toto" eType="#//Expression"/>
      <eParameters name="tata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subexprs" upperBound="-1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CellRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Cell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tableur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
